package rules

import app.models.Article;
import java.util.ArrayList;

rule "if article should be ordered"
	agenda-group "article_status"

    when
    	$article: Article(count < minCount)
    then
    	modify($article){
                    settatus(false)
                }

end

rule "if article should be ordered"
	agenda-group "article_status"

    when
    	$article: Article(count >= minCount)
    then
    	modify($article){
                    settatus(true)
                }

end